//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

/**
 * Helper class for marshaling/unmarshaling CandidateDataSeq.
 **/
public final class CandidateDataSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, CandidateData[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                CandidateData.ice_write(ostr, v[i0]);
            }
        }
    }

    public static CandidateData[] read(com.zeroc.Ice.InputStream istr)
    {
        final CandidateData[] v;
        final int len0 = istr.readAndCheckSeqSize(7);
        v = new CandidateData[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = CandidateData.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CandidateData[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, CandidateData[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            CandidateDataSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<CandidateData[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            CandidateData[] v;
            v = CandidateDataSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
