//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

public class CandidateResult implements java.lang.Cloneable,
                                        java.io.Serializable
{
    public int candidateId;

    public String candidateName;

    public int totalVotes;

    public CandidateResult()
    {
        this.candidateName = "";
    }

    public CandidateResult(int candidateId, String candidateName, int totalVotes)
    {
        this.candidateId = candidateId;
        this.candidateName = candidateName;
        this.totalVotes = totalVotes;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CandidateResult r = null;
        if(rhs instanceof CandidateResult)
        {
            r = (CandidateResult)rhs;
        }

        if(r != null)
        {
            if(this.candidateId != r.candidateId)
            {
                return false;
            }
            if(this.candidateName != r.candidateName)
            {
                if(this.candidateName == null || r.candidateName == null || !this.candidateName.equals(r.candidateName))
                {
                    return false;
                }
            }
            if(this.totalVotes != r.totalVotes)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ElectionSystem::CandidateResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, candidateId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, candidateName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalVotes);
        return h_;
    }

    public CandidateResult clone()
    {
        CandidateResult c = null;
        try
        {
            c = (CandidateResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.candidateId);
        ostr.writeString(this.candidateName);
        ostr.writeInt(this.totalVotes);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.candidateId = istr.readInt();
        this.candidateName = istr.readString();
        this.totalVotes = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CandidateResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CandidateResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        CandidateResult v = new CandidateResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CandidateResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CandidateResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CandidateResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CandidateResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CandidateResult _nullMarshalValue = new CandidateResult();

    /** @hidden */
    public static final long serialVersionUID = 2133483925L;
}
