//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

/**
 * Helper class for marshaling/unmarshaling CandidateResultSeq.
 **/
public final class CandidateResultSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, CandidateResult[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                CandidateResult.ice_write(ostr, v[i0]);
            }
        }
    }

    public static CandidateResult[] read(com.zeroc.Ice.InputStream istr)
    {
        final CandidateResult[] v;
        final int len0 = istr.readAndCheckSeqSize(9);
        v = new CandidateResult[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = CandidateResult.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CandidateResult[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, CandidateResult[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            CandidateResultSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<CandidateResult[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            CandidateResult[] v;
            v = CandidateResultSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
