//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

/**
 * Helper class for marshaling/unmarshaling CitizenDataSeq.
 **/
public final class CitizenDataSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, CitizenData[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                CitizenData.ice_write(ostr, v[i0]);
            }
        }
    }

    public static CitizenData[] read(com.zeroc.Ice.InputStream istr)
    {
        final CitizenData[] v;
        final int len0 = istr.readAndCheckSeqSize(11);
        v = new CitizenData[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = CitizenData.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CitizenData[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, CitizenData[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            CitizenDataSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<CitizenData[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            CitizenData[] v;
            v = CitizenDataSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
