//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

public class CitizenNotFound extends com.zeroc.Ice.UserException
{
    public CitizenNotFound()
    {
        this.reason = "";
    }

    public CitizenNotFound(Throwable cause)
    {
        super(cause);
        this.reason = "";
    }

    public CitizenNotFound(String reason)
    {
        this.reason = reason;
    }

    public CitizenNotFound(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::ElectionSystem::CitizenNotFound";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::ElectionSystem::CitizenNotFound", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1205825563L;
}
