//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

public class CitizenData implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public int id;

    public String document;

    public String firstName;

    public String lastName;

    public int tableId;

    public CitizenData()
    {
        this.document = "";
        this.firstName = "";
        this.lastName = "";
    }

    public CitizenData(int id, String document, String firstName, String lastName, int tableId)
    {
        this.id = id;
        this.document = document;
        this.firstName = firstName;
        this.lastName = lastName;
        this.tableId = tableId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CitizenData r = null;
        if(rhs instanceof CitizenData)
        {
            r = (CitizenData)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.document != r.document)
            {
                if(this.document == null || r.document == null || !this.document.equals(r.document))
                {
                    return false;
                }
            }
            if(this.firstName != r.firstName)
            {
                if(this.firstName == null || r.firstName == null || !this.firstName.equals(r.firstName))
                {
                    return false;
                }
            }
            if(this.lastName != r.lastName)
            {
                if(this.lastName == null || r.lastName == null || !this.lastName.equals(r.lastName))
                {
                    return false;
                }
            }
            if(this.tableId != r.tableId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ElectionSystem::CitizenData");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, document);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, firstName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tableId);
        return h_;
    }

    public CitizenData clone()
    {
        CitizenData c = null;
        try
        {
            c = (CitizenData)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.document);
        ostr.writeString(this.firstName);
        ostr.writeString(this.lastName);
        ostr.writeInt(this.tableId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.document = istr.readString();
        this.firstName = istr.readString();
        this.lastName = istr.readString();
        this.tableId = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CitizenData v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CitizenData ice_read(com.zeroc.Ice.InputStream istr)
    {
        CitizenData v = new CitizenData();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CitizenData> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CitizenData v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CitizenData> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CitizenData.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CitizenData _nullMarshalValue = new CitizenData();

    /** @hidden */
    public static final long serialVersionUID = -173479987L;
}
