//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

public interface ControlCenterServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default VotingTableData getVotingTableData(int tableId)
    {
        return getVotingTableData(tableId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default VotingTableData getVotingTableData(int tableId, java.util.Map<String, String> context)
    {
        return _iceI_getVotingTableDataAsync(tableId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<VotingTableData> getVotingTableDataAsync(int tableId)
    {
        return _iceI_getVotingTableDataAsync(tableId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<VotingTableData> getVotingTableDataAsync(int tableId, java.util.Map<String, String> context)
    {
        return _iceI_getVotingTableDataAsync(tableId, context, false);
    }

    /**
     * @hidden
     * @param iceP_tableId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<VotingTableData> _iceI_getVotingTableDataAsync(int iceP_tableId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<VotingTableData> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getVotingTableData", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_tableId);
                 }, istr -> {
                     VotingTableData ret;
                     ret = VotingTableData.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default CandidateData[] getCandidates()
    {
        return getCandidates(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CandidateData[] getCandidates(java.util.Map<String, String> context)
    {
        return _iceI_getCandidatesAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<CandidateData[]> getCandidatesAsync()
    {
        return _iceI_getCandidatesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CandidateData[]> getCandidatesAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCandidatesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CandidateData[]> _iceI_getCandidatesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CandidateData[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCandidates", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     CandidateData[] ret;
                     ret = CandidateDataSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void startElection()
    {
        startElection(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void startElection(java.util.Map<String, String> context)
    {
        _iceI_startElectionAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> startElectionAsync()
    {
        return _iceI_startElectionAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> startElectionAsync(java.util.Map<String, String> context)
    {
        return _iceI_startElectionAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_startElectionAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startElection", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void endElection()
    {
        endElection(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void endElection(java.util.Map<String, String> context)
    {
        _iceI_endElectionAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> endElectionAsync()
    {
        return _iceI_endElectionAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> endElectionAsync(java.util.Map<String, String> context)
    {
        return _iceI_endElectionAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_endElectionAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "endElection", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void submitVote(VoteData vote)
        throws CandidateNotFound,
               CitizenAlreadyVoted,
               CitizenNotBelongToTable,
               CitizenNotFound,
               ElectionInactive
    {
        submitVote(vote, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void submitVote(VoteData vote, java.util.Map<String, String> context)
        throws CandidateNotFound,
               CitizenAlreadyVoted,
               CitizenNotBelongToTable,
               CitizenNotFound,
               ElectionInactive
    {
        try
        {
            _iceI_submitVoteAsync(vote, context, true).waitForResponseOrUserEx();
        }
        catch(CandidateNotFound ex)
        {
            throw ex;
        }
        catch(CitizenAlreadyVoted ex)
        {
            throw ex;
        }
        catch(CitizenNotBelongToTable ex)
        {
            throw ex;
        }
        catch(CitizenNotFound ex)
        {
            throw ex;
        }
        catch(ElectionInactive ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> submitVoteAsync(VoteData vote)
    {
        return _iceI_submitVoteAsync(vote, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> submitVoteAsync(VoteData vote, java.util.Map<String, String> context)
    {
        return _iceI_submitVoteAsync(vote, context, false);
    }

    /**
     * @hidden
     * @param iceP_vote -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_submitVoteAsync(VoteData iceP_vote, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "submitVote", null, sync, _iceE_submitVote);
        f.invoke(true, context, null, ostr -> {
                     VoteData.ice_write(ostr, iceP_vote);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_submitVote =
    {
        CandidateNotFound.class,
        CitizenAlreadyVoted.class,
        CitizenNotBelongToTable.class,
        CitizenNotFound.class,
        ElectionInactive.class
    };

    default void subscribeElectionActivity(ElectionActivityObserverPrx observer, String votingTableIdentity)
    {
        subscribeElectionActivity(observer, votingTableIdentity, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeElectionActivity(ElectionActivityObserverPrx observer, String votingTableIdentity, java.util.Map<String, String> context)
    {
        _iceI_subscribeElectionActivityAsync(observer, votingTableIdentity, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeElectionActivityAsync(ElectionActivityObserverPrx observer, String votingTableIdentity)
    {
        return _iceI_subscribeElectionActivityAsync(observer, votingTableIdentity, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeElectionActivityAsync(ElectionActivityObserverPrx observer, String votingTableIdentity, java.util.Map<String, String> context)
    {
        return _iceI_subscribeElectionActivityAsync(observer, votingTableIdentity, context, false);
    }

    /**
     * @hidden
     * @param iceP_observer -
     * @param iceP_votingTableIdentity -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeElectionActivityAsync(ElectionActivityObserverPrx iceP_observer, String iceP_votingTableIdentity, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeElectionActivity", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_observer);
                     ostr.writeString(iceP_votingTableIdentity);
                 }, null);
        return f;
    }

    default void unsubscribeElectionActivity(String votingTableIdentity)
    {
        unsubscribeElectionActivity(votingTableIdentity, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unsubscribeElectionActivity(String votingTableIdentity, java.util.Map<String, String> context)
    {
        _iceI_unsubscribeElectionActivityAsync(votingTableIdentity, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unsubscribeElectionActivityAsync(String votingTableIdentity)
    {
        return _iceI_unsubscribeElectionActivityAsync(votingTableIdentity, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unsubscribeElectionActivityAsync(String votingTableIdentity, java.util.Map<String, String> context)
    {
        return _iceI_unsubscribeElectionActivityAsync(votingTableIdentity, context, false);
    }

    /**
     * @hidden
     * @param iceP_votingTableIdentity -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unsubscribeElectionActivityAsync(String iceP_votingTableIdentity, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unsubscribeElectionActivity", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_votingTableIdentity);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ControlCenterServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ControlCenterServicePrx.class, _ControlCenterServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ControlCenterServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ControlCenterServicePrx.class, _ControlCenterServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ControlCenterServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ControlCenterServicePrx.class, _ControlCenterServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ControlCenterServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ControlCenterServicePrx.class, _ControlCenterServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ControlCenterServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ControlCenterServicePrx.class, _ControlCenterServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ControlCenterServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ControlCenterServicePrx.class, _ControlCenterServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ControlCenterServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ControlCenterServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ControlCenterServicePrx ice_adapterId(String newAdapterId)
    {
        return (ControlCenterServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ControlCenterServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ControlCenterServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ControlCenterServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ControlCenterServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ControlCenterServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ControlCenterServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ControlCenterServicePrx ice_connectionCached(boolean newCache)
    {
        return (ControlCenterServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ControlCenterServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ControlCenterServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ControlCenterServicePrx ice_secure(boolean b)
    {
        return (ControlCenterServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ControlCenterServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ControlCenterServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ControlCenterServicePrx ice_preferSecure(boolean b)
    {
        return (ControlCenterServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ControlCenterServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ControlCenterServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ControlCenterServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ControlCenterServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ControlCenterServicePrx ice_collocationOptimized(boolean b)
    {
        return (ControlCenterServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ControlCenterServicePrx ice_twoway()
    {
        return (ControlCenterServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ControlCenterServicePrx ice_oneway()
    {
        return (ControlCenterServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ControlCenterServicePrx ice_batchOneway()
    {
        return (ControlCenterServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ControlCenterServicePrx ice_datagram()
    {
        return (ControlCenterServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ControlCenterServicePrx ice_batchDatagram()
    {
        return (ControlCenterServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ControlCenterServicePrx ice_compress(boolean co)
    {
        return (ControlCenterServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ControlCenterServicePrx ice_timeout(int t)
    {
        return (ControlCenterServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ControlCenterServicePrx ice_connectionId(String connectionId)
    {
        return (ControlCenterServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ControlCenterServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ControlCenterServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::ElectionSystem::ControlCenterService";
    }
}
