//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

public interface ServerServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default ElectionData getElectionData(int controlCenterId)
    {
        return getElectionData(controlCenterId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ElectionData getElectionData(int controlCenterId, java.util.Map<String, String> context)
    {
        return _iceI_getElectionDataAsync(controlCenterId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ElectionData> getElectionDataAsync(int controlCenterId)
    {
        return _iceI_getElectionDataAsync(controlCenterId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ElectionData> getElectionDataAsync(int controlCenterId, java.util.Map<String, String> context)
    {
        return _iceI_getElectionDataAsync(controlCenterId, context, false);
    }

    /**
     * @hidden
     * @param iceP_controlCenterId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ElectionData> _iceI_getElectionDataAsync(int iceP_controlCenterId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ElectionData> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getElectionData", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_controlCenterId);
                 }, istr -> {
                     ElectionData ret;
                     ret = ElectionData.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default VotingTableData[] getVotingTablesFromStation(int controlCenterId)
    {
        return getVotingTablesFromStation(controlCenterId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default VotingTableData[] getVotingTablesFromStation(int controlCenterId, java.util.Map<String, String> context)
    {
        return _iceI_getVotingTablesFromStationAsync(controlCenterId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<VotingTableData[]> getVotingTablesFromStationAsync(int controlCenterId)
    {
        return _iceI_getVotingTablesFromStationAsync(controlCenterId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<VotingTableData[]> getVotingTablesFromStationAsync(int controlCenterId, java.util.Map<String, String> context)
    {
        return _iceI_getVotingTablesFromStationAsync(controlCenterId, context, false);
    }

    /**
     * @hidden
     * @param iceP_controlCenterId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<VotingTableData[]> _iceI_getVotingTablesFromStationAsync(int iceP_controlCenterId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<VotingTableData[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getVotingTablesFromStation", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_controlCenterId);
                 }, istr -> {
                     VotingTableData[] ret;
                     ret = VotingTableDataSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void registerVote(VoteData vote)
        throws CandidateNotFound,
               CitizenAlreadyVoted,
               CitizenNotBelongToTable,
               CitizenNotFound
    {
        registerVote(vote, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerVote(VoteData vote, java.util.Map<String, String> context)
        throws CandidateNotFound,
               CitizenAlreadyVoted,
               CitizenNotBelongToTable,
               CitizenNotFound
    {
        try
        {
            _iceI_registerVoteAsync(vote, context, true).waitForResponseOrUserEx();
        }
        catch(CandidateNotFound ex)
        {
            throw ex;
        }
        catch(CitizenAlreadyVoted ex)
        {
            throw ex;
        }
        catch(CitizenNotBelongToTable ex)
        {
            throw ex;
        }
        catch(CitizenNotFound ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> registerVoteAsync(VoteData vote)
    {
        return _iceI_registerVoteAsync(vote, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerVoteAsync(VoteData vote, java.util.Map<String, String> context)
    {
        return _iceI_registerVoteAsync(vote, context, false);
    }

    /**
     * @hidden
     * @param iceP_vote -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerVoteAsync(VoteData iceP_vote, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerVote", null, sync, _iceE_registerVote);
        f.invoke(true, context, null, ostr -> {
                     VoteData.ice_write(ostr, iceP_vote);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_registerVote =
    {
        CandidateNotFound.class,
        CitizenAlreadyVoted.class,
        CitizenNotBelongToTable.class,
        CitizenNotFound.class
    };

    default void subscribe(EventObserverPrx observer, String observerIdentity)
    {
        subscribe(observer, observerIdentity, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribe(EventObserverPrx observer, String observerIdentity, java.util.Map<String, String> context)
    {
        _iceI_subscribeAsync(observer, observerIdentity, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeAsync(EventObserverPrx observer, String observerIdentity)
    {
        return _iceI_subscribeAsync(observer, observerIdentity, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeAsync(EventObserverPrx observer, String observerIdentity, java.util.Map<String, String> context)
    {
        return _iceI_subscribeAsync(observer, observerIdentity, context, false);
    }

    /**
     * @hidden
     * @param iceP_observer -
     * @param iceP_observerIdentity -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeAsync(EventObserverPrx iceP_observer, String iceP_observerIdentity, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribe", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_observer);
                     ostr.writeString(iceP_observerIdentity);
                 }, null);
        return f;
    }

    default void unsubscribe(String observerIdentity)
    {
        unsubscribe(observerIdentity, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unsubscribe(String observerIdentity, java.util.Map<String, String> context)
    {
        _iceI_unsubscribeAsync(observerIdentity, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unsubscribeAsync(String observerIdentity)
    {
        return _iceI_unsubscribeAsync(observerIdentity, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unsubscribeAsync(String observerIdentity, java.util.Map<String, String> context)
    {
        return _iceI_unsubscribeAsync(observerIdentity, context, false);
    }

    /**
     * @hidden
     * @param iceP_observerIdentity -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unsubscribeAsync(String iceP_observerIdentity, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unsubscribe", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_observerIdentity);
                 }, null);
        return f;
    }

    default CandidateData[] getCandidates()
    {
        return getCandidates(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CandidateData[] getCandidates(java.util.Map<String, String> context)
    {
        return _iceI_getCandidatesAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<CandidateData[]> getCandidatesAsync()
    {
        return _iceI_getCandidatesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CandidateData[]> getCandidatesAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCandidatesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CandidateData[]> _iceI_getCandidatesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CandidateData[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCandidates", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     CandidateData[] ret;
                     ret = CandidateDataSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default String findVotingStationByDocument(String document)
    {
        return findVotingStationByDocument(document, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String findVotingStationByDocument(String document, java.util.Map<String, String> context)
    {
        return _iceI_findVotingStationByDocumentAsync(document, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> findVotingStationByDocumentAsync(String document)
    {
        return _iceI_findVotingStationByDocumentAsync(document, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> findVotingStationByDocumentAsync(String document, java.util.Map<String, String> context)
    {
        return _iceI_findVotingStationByDocumentAsync(document, context, false);
    }

    /**
     * @hidden
     * @param iceP_document -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_findVotingStationByDocumentAsync(String iceP_document, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findVotingStationByDocument", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_document);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default CandidateResult[] getGlobalResults()
    {
        return getGlobalResults(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CandidateResult[] getGlobalResults(java.util.Map<String, String> context)
    {
        return _iceI_getGlobalResultsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<CandidateResult[]> getGlobalResultsAsync()
    {
        return _iceI_getGlobalResultsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CandidateResult[]> getGlobalResultsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getGlobalResultsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CandidateResult[]> _iceI_getGlobalResultsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CandidateResult[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGlobalResults", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     CandidateResult[] ret;
                     ret = CandidateResultSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default java.util.Map<java.lang.Integer, CandidateResult[]> getResultsByVotingTable()
    {
        return getResultsByVotingTable(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default java.util.Map<java.lang.Integer, CandidateResult[]> getResultsByVotingTable(java.util.Map<String, String> context)
    {
        return _iceI_getResultsByVotingTableAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<java.lang.Integer, CandidateResult[]>> getResultsByVotingTableAsync()
    {
        return _iceI_getResultsByVotingTableAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<java.lang.Integer, CandidateResult[]>> getResultsByVotingTableAsync(java.util.Map<String, String> context)
    {
        return _iceI_getResultsByVotingTableAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.util.Map<java.lang.Integer, CandidateResult[]>> _iceI_getResultsByVotingTableAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.Map<java.lang.Integer, CandidateResult[]>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getResultsByVotingTable", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     java.util.Map<java.lang.Integer, CandidateResult[]> ret;
                     ret = TableResultsMapHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServerServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ServerServicePrx.class, _ServerServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServerServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ServerServicePrx.class, _ServerServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServerServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ServerServicePrx.class, _ServerServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServerServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ServerServicePrx.class, _ServerServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ServerServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ServerServicePrx.class, _ServerServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ServerServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ServerServicePrx.class, _ServerServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ServerServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ServerServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ServerServicePrx ice_adapterId(String newAdapterId)
    {
        return (ServerServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ServerServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ServerServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ServerServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ServerServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ServerServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ServerServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ServerServicePrx ice_connectionCached(boolean newCache)
    {
        return (ServerServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ServerServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ServerServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServerServicePrx ice_secure(boolean b)
    {
        return (ServerServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ServerServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ServerServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServerServicePrx ice_preferSecure(boolean b)
    {
        return (ServerServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ServerServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ServerServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ServerServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ServerServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ServerServicePrx ice_collocationOptimized(boolean b)
    {
        return (ServerServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ServerServicePrx ice_twoway()
    {
        return (ServerServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ServerServicePrx ice_oneway()
    {
        return (ServerServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ServerServicePrx ice_batchOneway()
    {
        return (ServerServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ServerServicePrx ice_datagram()
    {
        return (ServerServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ServerServicePrx ice_batchDatagram()
    {
        return (ServerServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ServerServicePrx ice_compress(boolean co)
    {
        return (ServerServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ServerServicePrx ice_timeout(int t)
    {
        return (ServerServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ServerServicePrx ice_connectionId(String connectionId)
    {
        return (ServerServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ServerServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ServerServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::ElectionSystem::ServerService";
    }
}
