//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ElectionSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ElectionSystem;

public class VoteData implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String citizenDocument;

    public int candidateId;

    public int tableId;

    public String timestamp;

    public VoteData()
    {
        this.citizenDocument = "";
        this.timestamp = "";
    }

    public VoteData(String citizenDocument, int candidateId, int tableId, String timestamp)
    {
        this.citizenDocument = citizenDocument;
        this.candidateId = candidateId;
        this.tableId = tableId;
        this.timestamp = timestamp;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        VoteData r = null;
        if(rhs instanceof VoteData)
        {
            r = (VoteData)rhs;
        }

        if(r != null)
        {
            if(this.citizenDocument != r.citizenDocument)
            {
                if(this.citizenDocument == null || r.citizenDocument == null || !this.citizenDocument.equals(r.citizenDocument))
                {
                    return false;
                }
            }
            if(this.candidateId != r.candidateId)
            {
                return false;
            }
            if(this.tableId != r.tableId)
            {
                return false;
            }
            if(this.timestamp != r.timestamp)
            {
                if(this.timestamp == null || r.timestamp == null || !this.timestamp.equals(r.timestamp))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ElectionSystem::VoteData");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, citizenDocument);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, candidateId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tableId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        return h_;
    }

    public VoteData clone()
    {
        VoteData c = null;
        try
        {
            c = (VoteData)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.citizenDocument);
        ostr.writeInt(this.candidateId);
        ostr.writeInt(this.tableId);
        ostr.writeString(this.timestamp);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.citizenDocument = istr.readString();
        this.candidateId = istr.readInt();
        this.tableId = istr.readInt();
        this.timestamp = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, VoteData v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public VoteData ice_read(com.zeroc.Ice.InputStream istr)
    {
        VoteData v = new VoteData();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<VoteData> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, VoteData v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<VoteData> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(VoteData.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final VoteData _nullMarshalValue = new VoteData();

    /** @hidden */
    public static final long serialVersionUID = 1178119241L;
}
